openapi: 3.0.3
info:
  version: "1.0.0"
  title: "Example API - YAML"
  description: "Create Yaml interface from XML (File.xml)"

  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

  contact:
    name: "JP"
    url: "http://example.com"
    email: "example@domain.com"

servers:
    - url: https://virtserver.swaggerhub.com
    - url: http://dev.example.com
      description: Development Server

paths:
  /pets:
    get:
      summary: Get all pets from list
      tags:
        - "Pets List"
      description: Everything necessary about your pets
      operationId: getAllPetsList
      responses:
        '200':
          description: Get list of all pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pet'
            application/yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pet'
      security: []

    post:
      summary: Creating a new pet
      tags:
        - "Create pet"
      description: Everything necessary about your fake pets
      operationId: CreatePet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array                       #Mozna smazat?
              items:                            #Mozna smazat?
                $ref: '#/components/schemas/pet'
      responses:
        '201':
          description: Successfully created a new pet
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pet'
        '400':
          description: Bad request
        '409':
          description: Conflict


    patch:
      summary: Change pets information
      tags:
        - "Change information about pet"
      description: Change information about pet
      operationId: patchPetsList
      responses:
        200:
          description: success change information about pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pet'


    delete:
      summary: Delete pet from list
      tags:
        - "Delete pet from list"
      description: Delete your fake pet
      operationId: deletePetsList
      responses:
        200:
          description: success delete pet from the list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pet'

security:
  - BasicAuth: []
  - BearerAuth: []
  - ApiKeyAuth: []

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:
    pet:
      description: One of the pets
      type: object
      properties:
        category:
          description: Pets category
          type: object
          properties:
            id:
              description: Id of category
              type: integer
            name:
              description: Name of the animal species
              type: string
        id:
          description: Id of pet
          type: string
        name:
          description: Name of pet
          type: integer
        photoUrls:
          description: List of URL links to photos
          type: object
          properties:
            url:
              description: URL of the photo
              type: string
        tags:
          description: List of tags
          type: object
          properties:
            tag:
              description: guten tag
              type: string
