openapi: 3.0.3
info:
  version: "1.0.0"
  title: "Simple Artist API"
  description: "Create Yaml interface from XML (File.xml)"

  servers:
    - url: "https://example.com"
  contact:
    name: "JP"
    url: "http://example.com"
    email: "example@domain.com"

paths:
  /pets:
    description: "Everything necessary about your fake pets"
    get:
      description: "Return a list of pets"
      response:
        200:
          description: "success response a list of pets"
          content:
            application/json:
              schema:
                type: "object"
                items:
                  type: "object"
                  properties:
                    category:
                      type: "array"
                      id:
                        type: "integer"
                      name:
                        type: "string"
                    id:
                      type: "integer"
                    name:
                      type: "string"
                    photoUrls:
                      type: "array"
                      url: "string"
                    status:
                      type: "string"
                    tags:
                      type: "array"
                      tag:
                        type: "string"







            parameters:
              - in: "query"
                name: "category"
                required: "true"
                additionalProperties: "false"
                schema:
                  type: "array"
