openapi: 3.0.3
info:
  version: "1.0.0"
  title: "Example API - YAML"
  description: "Create Yaml interface from XML (File.xml)"

  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

  contact:
    name: "JP"
    url: "http://example.com"
    email: "example@domain.com"

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com

paths:
  /pets:
    get:
      summary: This is summary
      tags:
        - "Pets List"
      description: Everything necessary about your fake pets
      operationId: getAllPets
      responses:
        200:
          description: success response a list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pet'
            application/yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pet'



    patch:
      summary: Change pets information
      tags:
        - "Change information about pet"
      description: Change information about pet
      operationId: patchPetsList
      responses:
        200:
          description: success change information about pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pet'



    post:
      summary: Creating new pet to list
      tags:
        - "Create pet"
      description: Everything necessary about your fake pets
      operationId: postPetsList
      requestBody:
        content:
          application/json:
            properties:
              type: object
              items:
                $ref: '#/components/schemas/pet'
      responses:
        200:
          description: success create pet in the list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pet'
        404:
          description: Pet is invisible



    delete:
      summary: Delete pet from list
      tags:
        - "Delete pet from list"
      description: Delete your fake pet
      operationId: deletePetsList
      responses:
        200:
          description: success delete pet from the list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pet'


components:
  schemas:
    pet:
      description: One of the pets
      type: object
      properties:
        category:
          description: Pets category
          type: object
          properties:
            id:
              description: Id of category
              type: integer
            name:
              description: Name of the animal species
              type: string
        id:
          description: Id of pet
          type: string
        name:
          description: Name of pet
          type: integer
        photoUrls:
          description: List of URL links to photos
          type: object
          properties:
            url:
              description: URL of the photo
              type: string
        tags:
          description: List of tags
          type: object
          properties:
            tag:
              description: guten tag
              type: string
