openapi: 3.0.3
info:
  version: "1.0.0"
  title: "Example API - YAML"
  description: "Create Yaml interface from XML (File.xml)"

  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

  contact:
    name: "JP"
    url: "http://example.com"
    email: "example@domain.com"

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/peter.trahnyuk/testApi/1.0.0

paths:
  /pets/pet:
    get:
      summary: This is summary
      tags:
        - "Pets List"
      description: Everything necessary about your fake pets
      operationId: getAllPetsInZoo
      responses:
        200:
          description: success response a list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pet'



components:
  schemas:
    pet:
      description: One of the pets
      type: object
      properties:
        category:
          description: Pets category
          type: object
          properties:
            id:
              description: Id of category
              type: integer
            name:
              description: Name of the animal species
              type: string
        id:
          description: Id of pet
          type: string
        name:
          description: Name of pet
          type: integer
        photoUrls:
          description: List of URL links to photos
          type: object
          properties:
            url:
              description: URL of the photo
              type: string
        tags:
          description: List of tags
          type: object
          properties:
            tag:
              description: guten tag
              type: string
