//Hezky uvod do typescriptu, doplnil bych export modulu a generiku.
//Zde ani v JS jsem nenarazil na zminku o I/O blocking feature (nejsilnejsi zbran JS) -> event loop,
// co je callback hell, jak se resi promise pres await async atd...