GET http://localhost:3000/Hello HTTP/1.1  

###

//Overeni vytvoreni IB
GET http://localhost:3000 HTTP/1.1  

###

//Vytvoreni IB
POST http://localhost:3000/create-IB HTTP/1.1 
Content-Type: application/json

{
    "name": "Jan Peterek"
}

###
//Credit payment
POST http://localhost:3000/credit HTTP/1.1 
Content-Type: application/json

{
        "amount": 200,
        "currency": "CZK"
}

###

//Debit payment
POST http://localhost:3000/debit HTTP/1.1 
Content-Type: application/json

{
        "amount": 100,
        "currency": "EUR"
}

###




###

//Compare transactions by ID
POST http://localhost:3000/compareByIds HTTP/1.1
Content-Type: application/json

{
  "ids": [
    {"id": "a0f04e04d"},
    {"id": "17bd120ce5d"}
  ]
}



###



//Validace accountBallance < 0

//jenom jedna měna na učet == automaticky přepočet na CZK do EUR
//rozdil mezi fci map a filter
// opravit porovnani plateb tak aby bylo 1E == 26,5 CZK ve stejnem typu
//opravit simple generator ID .. jinak bez staticke promenné

//statické promenné
//FORM forming objection .. maping











# //Compare transactions by ID
# POST http://localhost:3000//compareByIds HTTP/1.1  
# Content-Type: application/json

# 

#  [2,25,8]

# 

//credit payment
# POST http://localhost:3000/credit-2 HTTP/1.1 
# Content-Type: application/json

# {
#         "amount": 50,
#         "currency": "EUR"
# }

###






